### PR TITLE
Update glossary.md

### PR DESCRIPTION
**Pull request by elgabbas**

### CODE REVIEW

**Comment by elgabbas** [comment]
aaa

**Comment by elgabbas** [comment]
I hope this does not cause any further conflicts

**Comment by florianhartig** [comment]
OK, I was mistaken yesterday, I thought everyone in biometry can edit, but it's not true - I will put you in the editing group, OK? 

You can still to the fork / pull if you prefer

F

**Comment by elgabbas** [comment]
Which is more safer? if forking, editing and then pulling does not make a lot of approval load on you (and no much conflicts like yesterday), it may be better?

**Comment by florianhartig** [comment]
I think for a real software project forking would be safer - if you want to train it you can keep on doing it, but if you just change a few words and stuff like that, you can also work directly in Apes, it's no problem.

**Comment by elgabbas** [comment]
OK, great

**Pull request merged**
