### PR TITLE
Update hub-experimentalDesign.md

### PR DESCRIPTION
**Pull request by elgabbas**

### CODE REVIEW

**Comment by florianhartig** [comment]
Hi Ahmed,

I think this will go wrong if we push this on the main page, because they have different roots. I think this path must be old. The new thing would be to have full paths (to the main website, the nice looking one) in all md file. 

Can you revise the pull request, or do I have to deny it and you do a new one?

Two more things

* If there is a Rmd file, changes should be in Rmd and not in md, because the md is created from the Rmd

* I'm not sure about the html _blank tags for opening new pages. It should be fine, but for easier maintenance I would prefer the md standard of [text](link) ... doesn't open in new tab, but there is a bit of disagreement if that's a good thing anyway

**Comment by elgabbas** [comment]
I do not know how you create html webpages from the github respository into github.io
I use the ../ to move to the parent directory (out from hub then to checklist folder). You use different pronounciation in both (Checklists / checklists)
For now, please ignore this pull request.
A

**Comment by florianhartig** [comment]
I think the link may have been a problem, so it's OK to change it, just use the full link to the html site. I'll do it for this file now. 

The issue is that there is a different root, and things are partly differently displayed on the bare gh pages and on the html version. The save thing thus for all links is simply to use as target the html page http://biometry.github.io/APES/ And, in doubt, check if the code as it is now works on the html version http://biometry.github.io/APES/

I'm pushing the stuff to the gh-i/o btw, it's a separate branch.

**Comment by florianhartig** [comment]
see https://github.com/biometry/APES/commit/d99b12e9056a7a0ae4875094b9ba994f688ea347#diff-d26f10a82d3695d473ad2ea585a7f28d

**Pull request closed without merging**
